# HTTP Server
server:
  port: 16346  # HTTP (Tomcat) port

spring:
  application:
    name: ts-travel2-service
  datasource:
    url: jdbc:mysql://${TRAVEL2_MYSQL_HOST:ts-travel2-mysql}:${TRAVEL2_MYSQL_PORT:3306}/${TRAVEL2_MYSQL_DATABASE:ts}?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: ${TRAVEL2_MYSQL_USER:root}
    password: ${TRAVEL2_MYSQL_PASSWORD:zhaoyiming.18}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
swagger:
  controllerPackage: travel2.controller

eureka:
  client:
    serviceUrl:
      defaultZone: http://ts-discovery-service:8761/eureka/
