server:
  port: 12386

spring:
  application:
    name: ts-execute-service
swagger:
  controllerPackage: execute.controller

eureka:
  client:
    serviceUrl:
      defaultZone: http://ts-discovery-service:8761/eureka/
