
services:
  ts-price-mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: zhaoyiming.18
      MYSQL_DATABASE: ts
    ports:
      - 3306:3306
    networks:
      - my-network

  ts-discovery-service:
    image: ${NAMESPACE}/ts-discovery-service:${TAG}
    restart: always
    container_name: ts-discovery-service
    hostname: ts-discovery-service
    ports:
      - 8761:8761
    networks:
      - my-network

#  ts-order-other-service:
#    image: ${NAMESPACE}/ts-order-other-service:${TAG}
#    restart: always
#    ports:
#      - 12032:12032
#    networks:
#      - my-network
#    environment:
#      - ORDER_OTHER_MYSQL_HOST=ts-price-mysql
#      - ORDER_OTHER_MYSQL_PORT=3306
#      - ORDER_OTHER_MYSQL_DATABASE=ts
#      - ORDER_OTHER_MYSQL_USER=root
#      - ORDER_OTHER_MYSQL_PASSWORD=zhaoyiming.18
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#    depends_on:
#      - ts-price-mysql
#      - ts-discovery-service
#
#  ts-train-service:
#    image: ${NAMESPACE}/ts-train-service:${TAG}
#    restart: always
#    ports:
#      - 14567:14567
#    networks:
#      - my-network
#    environment:
#      - TRAIN_MYSQL_HOST=ts-price-mysql
#      - TRAIN_MYSQL_PORT=3306
#      - TRAIN_MYSQL_DATABASE=ts
#      - TRAIN_MYSQL_USER=root
#      - TRAIN_MYSQL_PASSWORD=zhaoyiming.18
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#    depends_on:
#      - ts-price-mysql
#      - ts-discovery-service
#
#  ts-route-service:
#    image: ${NAMESPACE}/ts-route-service:${TAG}
#    restart: always
#    ports:
#      - 11178:11178
#    networks:
#      - my-network
#    environment:
#      - ROUTE_MYSQL_HOST=ts-price-mysql
#      - ROUTE_MYSQL_PORT=3306
#      - ROUTE_MYSQL_DATABASE=ts
#      - ROUTE_MYSQL_USER=root
#      - ROUTE_MYSQL_PASSWORD=zhaoyiming.18
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#    depends_on:
#      - ts-price-mysql
#      - ts-discovery-service

#  ts-contacts-service:
#    image: ${NAMESPACE}/ts-contacts-service:${TAG}
#    restart: always
#    ports:
#      - 12347:12347
#    networks:
#      - my-network
#    environment:
#      - CONTACT_MYSQL_HOST=ts-price-mysql
#      - CONTACT_MYSQL_PORT=3306
#      - CONTACT_MYSQL_DATABASE=ts
#      - CONTACT_MYSQL_USER=root
#      - CONTACT_MYSQL_PASSWORD=zhaoyiming.18
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#    depends_on:
#      - ts-price-mysql
#      - ts-discovery-service
#
#  ts-admin-basic-info-service:
#    image: ${NAMESPACE}/ts-admin-basic-info-service:${TAG}
#    restart: always
#    ports:
#      - 18767:18767
#    networks:
#      - my-network
#    environment:
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#    depends_on:
#      - ts-discovery-service
#
#  ts-price-service:
#    image: ${NAMESPACE}/ts-price-service:${TAG}
#    restart: always
#    ports:
#      - 16579:16579
#    networks:
#      - my-network
#    environment:
#      - PRICE_MYSQL_HOST=ts-price-mysql
#      - PRICE_MYSQL_PORT=3306
#      - PRICE_MYSQL_DATABASE=ts
#      - PRICE_MYSQL_USER=root
#      - PRICE_MYSQL_PASSWORD=zhaoyiming.18
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#    depends_on:
#      - ts-price-mysql
#      - ts-discovery-service
#
#  ts-station-service:
#    image: ${NAMESPACE}/ts-station-service:${TAG}
#    restart: always
#    ports:
#      - 12345:12345
#    networks:
#      - my-network
#    environment:
#      - STATION_MYSQL_HOST=ts-price-mysql
#      - STATION_MYSQL_PORT=3306
#      - STATION_MYSQL_DATABASE=ts
#      - STATION_MYSQL_USER=root
#      - STATION_MYSQL_PASSWORD=zhaoyiming.18
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#    depends_on:
#      - ts-price-mysql
#      - ts-discovery-service

#  ts-basic-service:
#    image: ${NAMESPACE}/ts-basic-service:${TAG}
#    restart: always
#    ports:
#      - 15680:15680
#    networks:
#      - my-network
#    environment:
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#    depends_on:
#      - ts-discovery-service
#
#  ts-order-service:
#    image: ${NAMESPACE}/ts-order-service:${TAG}
#    restart: always
#    ports:
#      - 12031:12031
#    networks:
#      - my-network
#    environment:
#      - ORDER_MYSQL_HOST=ts-price-mysql
#      - ORDER_MYSQL_PORT=3306
#      - ORDER_MYSQL_DATABASE=ts
#      - ORDER_MYSQL_USER=root
#      - ORDER_MYSQL_PASSWORD=zhaoyiming.18
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#    depends_on:
#      - ts-price-mysql
#      - ts-discovery-service
#
#  ts-seat-service:
#    image: ${NAMESPACE}/ts-seat-service:${TAG}
#    restart: always
#    ports:
#      - 18898:18898
#    networks:
#      - my-network
#    environment:
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#    depends_on:
#      - ts-discovery-service

#   ts-train-food-service:
#    image: ${NAMESPACE}/ts-train-food-service:${TAG}
#    restart: always
#    ports:
#      - 19999:19999
#    networks:
#      - my-network
#    environment:
#      - TRAIN_FOOD_MYSQL_HOST=ts-price-mysql
#      - TRAIN_FOOD_MYSQL_PORT=3306
#      - TRAIN_FOOD_MYSQL_DATABASE=ts
#      - TRAIN_FOOD_MYSQL_USER=root
#      - TRAIN_FOOD_MYSQL_PASSWORD=zhaoyiming.18
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#    depends_on:
#      - ts-price-mysql
#      - ts-discovery-service

#  ts-admin-order-service:
#      image: ${NAMESPACE}/ts-admin-order-service:${TAG}
#      restart: always
#      ports:
#        - 16112:16112
#      networks:
#        - my-network
#      environment:
#        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#      depends_on:
#        - ts-discovery-service
#
#  ts-admin-user-service:
#      image: ${NAMESPACE}/ts-admin-user-service:${TAG}
#      restart: always
#      ports:
#        - 16115:16115
#      networks:
#        - my-network
#      environment:
#        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#      depends_on:
#        - ts-discovery-service
#
#  ts-assurance-service:
#      image: ${NAMESPACE}/ts-assurance-service:${TAG}
#      restart: always
#      ports:
#        - 18888:18888
#      networks:
#        - my-network
#      environment:
#        - ASSURANCE_MYSQL_HOST=ts-price-mysql
#        - ASSURANCE_MYSQL_PORT=3306
#        - ASSURANCE_MYSQL_DATABASE=ts
#        - ASSURANCE_MYQL_USER=root
#        - ASSURANCE_MYSQL_PASSWORD=zhaoyiming.18
#        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#      depends_on:
#        - ts-discovery-service

  ts-user-service:
      image: ${NAMESPACE}/ts-user-service:${TAG}
      restart: always
      ports:
        - 12342:12342
      networks:
        - my-network
      environment:
        - USER_MYSQL_HOST=ts-price-mysql
        - USER_MYSQL_PORT=3306
        - USER_MYSQL_DATABASE=ts
        - USER_MYSQL_USER=root
        - USER_MYSQL_PASSWORD=zhaoyiming.18
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
      depends_on:
        - ts-discovery-service

networks:
  my-network:
    driver: bridge


