
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - my-network

  ts-price-mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: zhaoyiming.18
      MYSQL_DATABASE: ts
    ports:
      - 3306:3306
    networks:
      - my-network

  ts-discovery-service:
    image: ${NAMESPACE}/ts-discovery-service:${TAG}
    restart: always
    container_name: ts-discovery-service
    hostname: ts-discovery-service
    ports:
      - 8761:8761
    networks:
      - my-network

  ts-security-service:
    image: ${NAMESPACE}/ts-security-service:${TAG}
    restart: always
    container_name: ts-security-service
    hostname: ts-security-service
    ports:
      - 11188:11188
    networks:
      - my-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
      - SECURITY_MYSQL_HOST=ts-price-mysql
      - SECURITY_MYSQL_PORT=3306
      - SECURITY_MYSQL_DATABASE=ts
      - SECURITY_MYSQL_USER=root
      - SECURITY_MYSQL_PASSWORD=zhaoyiming.18

  ts-travel-plan-service:
    image: ${NAMESPACE}/ts-travel-plan-service:${TAG}
    restart: always
    container_name: ts-travel-plan-service
    hostname: ts-travel-plan-service
    ports:
      - 14322:14322
    networks:
      - my-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - ts-discovery-service

  ts-route-plan-service:
    image: ${NAMESPACE}/ts-route-plan-service:${TAG}
    restart: always
    container_name: ts-route-plan-service
    hostname: ts-route-plan-service
    ports:
      - 14578:14578
    networks:
      - my-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - ts-discovery-service

  ts-rebook-service:
    image: ${NAMESPACE}/ts-rebook-service:${TAG}
    restart: always
    container_name: ts-rebook-service
    hostname: ts-rebook-service
    ports:
      - 18886:18886
    networks:
      - my-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
    depends_on:
      - ts-discovery-service


#  ts-food-service:
#    image: ${NAMESPACE}/ts-food-service:${TAG}
#    restart: always
#    container_name: ts-food-service
#    hostname: ts-food-service
#    ports:
#      - 18856:18856
#    networks:
#      - my-network
#    environment:
#      - FOOD_MYSQL_HOST=ts-price-mysql
#      - FOOD_MYSQL_PORT=3306
#      - FOOD_MYSQL_DATABASE=ts
#      - FOOD_MYSQL_USER=root
#      - FOOD_MYSQL_PASSWORD=zhaoyiming.18
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#      - RABBITMQ_HOST=rabbitmq
#    depends_on:
#      - ts-discovery-service
#      - ts-price-mysql
#      - rabbitmq
#  ts-config-service:
#    image: ${NAMESPACE}/ts-config-service:${TAG}
#    restart: always
#    container_name: ts-config-service
#    hostname: ts-config-service
#    ports:
#      - 15679:15679
#    networks:
#      - my-network
#    environment:
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#      - CONFIG_MYSQL_HOST=ts-price-mysql
#      - CONFIG_MYSQL_PORT=3306
#      - CONFIG_MYSQL_DATABASE=ts
#      - CONFIG_MYSQL_USER=root
#      - CONFIG_MYSQL_PASSWORD=zhaoyiming.18
#
#  ts-preserve-other-service:
#    image: ${NAMESPACE}/ts-preserve-other-service:${TAG}
#    restart: always
#    container_name: ts-preserve-other-service
#    hostname: ts-preserve-other-service
#    ports:
#       - 14569:14569
#    networks:
#        - my-network
#    environment:
#        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#         - RABBITMQ_HOST=rabbitmq
#    depends_on:
#        - ts-discovery-service
#        - ts-price-mysql
#
#  ts-wait-order-service:
#    image: ${NAMESPACE}/ts-wait-order-service:${TAG}
#    restart: always
#    container_name: ts-wait-order-service
#    hostname: ts-wait-order-service
#    ports:
#      - 17525:17525
#    networks:
#      - my-network
#    environment:
#      - WAIT_ORDER_MYSQL_HOST=ts-price-mysql
#      - WAIT_ORDER_MYSQL_PORT=3306
#      - WAIT_ORDER_MYSQL_DATABASE=ts
#      - WAIT_ORDER_MYSQL_USER=root
#      - WAIT_ORDER_MYSQL_PASSWORD=zhaoyiming.18
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#    depends_on:
#      - ts-discovery-service
#      - ts-price-mysql
#
#  ts-station-food-service:
#    image: ${NAMESPACE}/ts-station-food-service:${TAG}
#    restart: always
#    container_name: ts-station-food-service
#    hostname: ts-station-food-service
#    ports:
#      - 18855:18855
#    networks:
#      - my-network
#    environment:
#      - STATION_FOOD_MYSQL_HOST=ts-price-mysql
#      - STATION_FOOD_MYSQL_PORT=3306
#      - STATION_FOOD_MYSQL_DATABASE=ts
#      - STATION_FOOD_MYSQL_USER=root
#      - STATION_FOOD_MYSQL_PASSWORD=zhaoyiming.18
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#    depends_on:
#      - ts-discovery-service
#      - ts-price-mysql
#
#  ts-preserve-service:
#    image: ${NAMESPACE}/ts-preserve-service:${TAG}
#    restart: always
#    container_name: ts-preserve-service
#    hostname: ts-preserve-service
#    ports:
#      - 14568:14568
#    networks:
#      - my-network
#    environment:
#      - PRESERVE_MYSQL_HOST=ts-price-mysql
#      - PRESERVE_MYSQL_PORT=3306
#      - PRESERVE_MYSQL_DATABASE=ts
#      - PRESERVE_MYSQL_USER=root
#      - PRESERVE_MYSQL_PASSWORD=zhaoyiming.18
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#      - RABBITMQ_HOST=rabbitmq
#    depends_on:
#      - ts-discovery-service
#      - ts-price-mysql
#      - rabbitmq
#
#
#  ts-food-delivery-service:
#    image: ${NAMESPACE}/ts-food-delivery-service:${TAG}
#    restart: always
#    container_name: ts-food-delivery-service
#    hostname: ts-food-delivery-service
#    ports:
#      - 18957:18957
#    networks:
#      - my-network
#    environment:
#      - FOOD_DELIVERY_MYSQL_HOST=ts-price-mysql
#      - FOOD_DELIVERY_MYSQL_PORT=3306
#      - FOOD_DELIVERY_MYSQL_DATABASE=ts
#      - FOOD_DELIVERY_MYSQL_USER=root
#      - FOOD_DELIVERY_MYSQL_PASSWORD=zhaoyiming.18
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#      - RABBITMQ_HOST=rabbitmq
#    depends_on:
#      - ts-discovery-service
#      - ts-price-mysql
#      - rabbitmq
#

#  ts-execute-service:
#    image: ${NAMESPACE}/ts-execute-service:${TAG}
#    restart: always
#    container_name: ts-execute-service
#    hostname: ts-execute-service
#    ports:
#      - 12386:12386
#    networks:
#      - my-network
#    environment:
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#    depends_on:
#      - ts-discovery-service
#
#  ts-travel-service:
#    image: ${NAMESPACE}/ts-travel-service:${TAG}
#    restart: always
#    container_name: ts-travel-service
#    hostname: ts-travel-service
#    ports:
#      - 12346:12346
#    networks:
#      - my-network
#    environment:
#      - TRAVEL_MYSQL_HOST=ts-price-mysql
#      - TRAVEL_MYSQL_PORT=3306
#      - TRAVEL_MYSQL_DATABASE=ts
#      - TRAVEL_MYSQL_USER=root
#      - TRAVEL_MYSQL_PASSWORD=zhaoyiming.18
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#    depends_on:
#      - ts-price-mysql
#      - ts-discovery-service
#
#  ts-travel2-service:
#    image: ${NAMESPACE}/ts-travel2-service:${TAG}
#    restart: always
#    container_name: ts-travel2-service
#    hostname: ts-travel2-service
#    ports:
#      - 16346:16346
#    networks:
#      - my-network
#    environment:
#      - TRAVEL2_MYSQL_HOST=ts-price-mysql
#      - TRAVEL2_MYSQL_PORT=3306
#      - TRAVEL2_MYSQL_DATABASE=ts
#      - TRAVEL2_MYSQL_USER=root
#      - TRAVEL2_MYSQL_PASSWORD=zhaoyiming.18
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#    depends_on:
#      - ts-price-mysql
#      - ts-discovery-service
#
#
#  ts-order-other-service:
#    image: ${NAMESPACE}/ts-order-other-service:${TAG}
#    restart: always
#    ports:
#      - 12032:12032
#    networks:
#      - my-network
#    environment:
#      - ORDER_OTHER_MYSQL_HOST=ts-price-mysql
#      - ORDER_OTHER_MYSQL_PORT=3306
#      - ORDER_OTHER_MYSQL_DATABASE=ts
#      - ORDER_OTHER_MYSQL_USER=root
#      - ORDER_OTHER_MYSQL_PASSWORD=zhaoyiming.18
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#    depends_on:
#      - ts-price-mysql
#      - ts-discovery-service
#
#  ts-train-service:
#    image: ${NAMESPACE}/ts-train-service:${TAG}
#    restart: always
#    ports:
#      - 14567:14567
#    networks:
#      - my-network
#    environment:
#      - TRAIN_MYSQL_HOST=ts-price-mysql
#      - TRAIN_MYSQL_PORT=3306
#      - TRAIN_MYSQL_DATABASE=ts
#      - TRAIN_MYSQL_USER=root
#      - TRAIN_MYSQL_PASSWORD=zhaoyiming.18
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#    depends_on:
#      - ts-price-mysql
#      - ts-discovery-service
#
#  ts-route-service:
#    image: ${NAMESPACE}/ts-route-service:${TAG}
#    restart: always
#    ports:
#      - 11178:11178
#    networks:
#      - my-network
#    environment:
#      - ROUTE_MYSQL_HOST=ts-price-mysql
#      - ROUTE_MYSQL_PORT=3306
#      - ROUTE_MYSQL_DATABASE=ts
#      - ROUTE_MYSQL_USER=root
#      - ROUTE_MYSQL_PASSWORD=zhaoyiming.18
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#    depends_on:
#      - ts-price-mysql
#      - ts-discovery-service
#  ts-basic-service:
#    image: ${NAMESPACE}/ts-basic-service:${TAG}
#    restart: always
#    ports:
#      - 15680:15680
#    networks:
#      - my-network
#    environment:
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#    depends_on:
#      - ts-discovery-service
#
#  ts-order-service:
#    image: ${NAMESPACE}/ts-order-service:${TAG}
#    restart: always
#    ports:
#      - 12031:12031
#    networks:
#      - my-network
#    environment:
#      - ORDER_MYSQL_HOST=ts-price-mysql
#      - ORDER_MYSQL_PORT=3306
#      - ORDER_MYSQL_DATABASE=ts
#      - ORDER_MYSQL_USER=root
#      - ORDER_MYSQL_PASSWORD=zhaoyiming.18
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#    depends_on:
#      - ts-price-mysql
#      - ts-discovery-service
#
#  ts-seat-service:
#    image: ${NAMESPACE}/ts-seat-service:${TAG}
#    restart: always
#    ports:
#      - 18898:18898
#    networks:
#      - my-network
#    environment:
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#    depends_on:
#      - ts-discovery-service
#
#  ts-station-service:
#    image: ${NAMESPACE}/ts-station-service:${TAG}
#    restart: always
#    ports:
#      - 12345:12345
#    networks:
#      - my-network
#    environment:
#      - STATION_MYSQL_HOST=ts-price-mysql
#      - STATION_MYSQL_PORT=3306
#      - STATION_MYSQL_DATABASE=ts
#      - STATION_MYSQL_USER=root
#      - STATION_MYSQL_PASSWORD=zhaoyiming.18
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#    depends_on:
#      - ts-price-mysql
#      - ts-discovery-service

#  ts-contacts-service:
#    image: ${NAMESPACE}/ts-contacts-service:${TAG}
#    restart: always
#    ports:
#      - 12347:12347
#    networks:
#      - my-network
#    environment:
#      - CONTACT_MYSQL_HOST=ts-price-mysql
#      - CONTACT_MYSQL_PORT=3306
#      - CONTACT_MYSQL_DATABASE=ts
#      - CONTACT_MYSQL_USER=root
#      - CONTACT_MYSQL_PASSWORD=zhaoyiming.18
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#    depends_on:
#      - ts-price-mysql
#      - ts-discovery-service
#
#  ts-admin-basic-info-service:
#    image: ${NAMESPACE}/ts-admin-basic-info-service:${TAG}
#    restart: always
#    ports:
#      - 18767:18767
#    networks:
#      - my-network
#    environment:
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#    depends_on:
#      - ts-discovery-service
#
#  ts-price-service:
#    image: ${NAMESPACE}/ts-price-service:${TAG}
#    restart: always
#    ports:
#      - 16579:16579
#    networks:
#      - my-network
#    environment:
#      - PRICE_MYSQL_HOST=ts-price-mysql
#      - PRICE_MYSQL_PORT=3306
#      - PRICE_MYSQL_DATABASE=ts
#      - PRICE_MYSQL_USER=root
#      - PRICE_MYSQL_PASSWORD=zhaoyiming.18
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#    depends_on:
#      - ts-price-mysql
#      - ts-discovery-service
#

#   ts-train-food-service:
#    image: ${NAMESPACE}/ts-train-food-service:${TAG}
#    restart: always
#    ports:
#      - 19999:19999
#    networks:
#      - my-network
#    environment:
#      - TRAIN_FOOD_MYSQL_HOST=ts-price-mysql
#      - TRAIN_FOOD_MYSQL_PORT=3306
#      - TRAIN_FOOD_MYSQL_DATABASE=ts
#      - TRAIN_FOOD_MYSQL_USER=root
#      - TRAIN_FOOD_MYSQL_PASSWORD=zhaoyiming.18
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#    depends_on:
#      - ts-price-mysql
#      - ts-discovery-service

#  ts-admin-order-service:
#      image: ${NAMESPACE}/ts-admin-order-service:${TAG}
#      restart: always
#      ports:
#        - 16112:16112
#      networks:
#        - my-network
#      environment:
#        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#      depends_on:
#        - ts-discovery-service
#
#  ts-admin-user-service:
#      image: ${NAMESPACE}/ts-admin-user-service:${TAG}
#      restart: always
#      ports:
#        - 16115:16115
#      networks:
#        - my-network
#      environment:
#        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#      depends_on:
#        - ts-discovery-service
#
#  ts-assurance-service:
#      image: ${NAMESPACE}/ts-assurance-service:${TAG}
#      restart: always
#      ports:
#        - 18888:18888
#      networks:
#        - my-network
#      environment:
#        - ASSURANCE_MYSQL_HOST=ts-price-mysql
#        - ASSURANCE_MYSQL_PORT=3306
#        - ASSURANCE_MYSQL_DATABASE=ts
#        - ASSURANCE_MYQL_USER=root
#        - ASSURANCE_MYSQL_PASSWORD=zhaoyiming.18
#        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#      depends_on:
#        - ts-discovery-service
#
#  ts-user-service:
#      image: ${NAMESPACE}/ts-user-service:${TAG}
#      restart: always
#      ports:
#        - 12342:12342
#      networks:
#        - my-network
#      environment:
#        - USER_MYSQL_HOST=ts-price-mysql
#        - USER_MYSQL_PORT=3306
#        - USER_MYSQL_DATABASE=ts
#        - USER_MYSQL_USER=root
#        - USER_MYSQL_PASSWORD=zhaoyiming.18
#        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#      depends_on:
#        - ts-discovery-service
#
#  ts-admin-route-service:
#      image: ${NAMESPACE}/ts-admin-route-service:${TAG}
#      restart: always
#      ports:
#        - 16113:16113
#      networks:
#        - my-network
#      environment:
#        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#      depends_on:
#        - ts-discovery-service
#
#  ts-admin-travel-service:
#      image: ${NAMESPACE}/ts-admin-travel-service:${TAG}
#      restart: always
#      ports:
#        - 16114:16114
#      networks:
#        - my-network
#      environment:
#        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#      depends_on:
#        - ts-discovery-service
#
#  ts-consign-service:
#      image: ${NAMESPACE}/ts-consign-service:${TAG}
#      restart: always
#      ports:
#        - 16111:16111
#      networks:
#        - my-network
#      environment:
#        - CONSIGN_MYSQL_HOST=ts-price-mysql
#        - CONSIGN_MYSQL_PORT=3306
#        - CONSIGN_MYSQL_DATABASE=ts
#        - CONSIGN_MYSQL_USER=root
#        - CONSIGN_MYSQL_PASSWORD=zhaoyiming.18
#        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#      depends_on:
#        - ts-price-mysql
#        - ts-discovery-service
#
#  ts-consign-price-service:
#      image: ${NAMESPACE}/ts-consign-price-service:${TAG}
#      restart: always
#      ports:
#        - 16110:16110
#      networks:
#        - my-network
#      environment:
#        - CONSIGN_PRICE_MYSQL_HOST=ts-price-mysql
#        - CONSIGN_PRICE_MYSQL_PORT=3306
#        - CONSIGN_PRICE_MYSQL_DATABASE=ts
#        - CONSIGN_PRICE_MYSQL_USER=root
#        - CONSIGN_PRICE_MYSQL_PASSWORD=zhaoyiming.18
#        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
#      depends_on:
#        - ts-price-mysql
#        - ts-discovery-service


networks:
  my-network:
    driver: bridge


