
services:
  ts-discovery-service:
    image: ${NAMESPACE}/ts-discovery-service:${TAG}
    restart: always
    container_name: ts-discovery-service
    hostname: ts-discovery-service
    ports:
      - 8761:8761
    networks:
      - my-network

  ts-price-service:
    image: ${NAMESPACE}/ts-price-service:${TAG}
    restart: always
    ports:
      - 16579:16579
    networks:
      - my-network
    environment:
      - PRICE_MYSQL_HOST=ts-price-mysql
      - PRICE_MYSQL_PORT=3306
      - PRICE_MYSQL_DATABASE=ts
      - PRICE_MYSQL_USER=root
      - PRICE_MYSQL_PASSWORD=zhaoyiming.18
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
    depends_on:
      - ts-price-mysql
      - ts-discovery-service

  ts-station-service:
    image: ${NAMESPACE}/ts-station-service:${TAG}
    restart: always
    ports:
      - 12345:12345
    networks:
      - my-network
    environment:
      - STATION_MYSQL_HOST=ts-price-mysql
      - STATION_MYSQL_PORT=3306
      - STATION_MYSQL_DATABASE=ts
      - STATION_MYSQL_USER=root
      - STATION_MYSQL_PASSWORD=zhaoyiming.18
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
    depends_on:
      - ts-price-mysql
      - ts-discovery-service

  ts-train-food-service:
    image: ${NAMESPACE}/ts-train-food-service:${TAG}
    restart: always
    ports:
      - 19999:19999
    networks:
      - my-network
    environment:
      - TRAIN_FOOD_MYSQL_HOST=ts-price-mysql
      - TRAIN_FOOD_MYSQL_PORT=3306
      - TRAIN_FOOD_MYSQL_DATABASE=ts
      - TRAIN_FOOD_MYSQL_USER=root
      - TRAIN_FOOD_MYSQL_PASSWORD=zhaoyiming.18
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ts-discovery-service:8761/eureka/
    depends_on:
      - ts-price-mysql
      - ts-discovery-service

  ts-price-mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: zhaoyiming.18
      MYSQL_DATABASE: ts
    ports:
      - 3306:3306
    networks:
      - my-network

networks:
  my-network:
    driver: bridge


