server:
  port: 18957

spring:
  application:
    name: ts-food-delivery-service
  datasource:
#    url: jdbc:mysql://localhost:30001/ts-food-delivery-mysql?useSSL=false
    url: jdbc:mysql://${FOOD_DELIVERY_MYSQL_HOST:ts-food-delivery-mysql}:${FOOD_DELIVERY_MYSQL_PORT:3306}/${FOOD_DELIVERY_MYSQL_DATABASE:ts}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${FOOD_DELIVERY_MYSQL_USER:root}
    password: ${FOOD_DELIVERY_MYSQL_PASSWORD:Abc123%}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://127.0.0.1:8761/eureka/}
      preferIpAddress: true

swagger:
  controllerPackage: fooddelivery.controller