# HTTP Server
server:
  port: 19001  # HTTP (Tomcat) port

spring:
  application:
    name: ts-payment-service
  datasource:
    url: jdbc:mysql://${PAYMENT_MYSQL_HOST:ts-payment-mysql}:${PAYMENT_MYSQL_PORT:3306}/${PAYMENT_MYSQL_DATABASE:ts}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${PAYMENT_MYSQL_USER:root}
    password: ${PAYMENT_MYSQL_PASSWORD:zhaoyiming.18}
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

swagger:
  controllerPackage: com.trainticket.controller

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://127.0.0.1:8761/eureka/}
      preferIpAddress: true
