spring:
  application:
    name: ts-price-service
  datasource:
    url: jdbc:mysql://${PRICE_MYSQL_HOST}:${PRICE_MYSQL_PORT:3306}/${PRICE_MYSQL_DATABASE:ts}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${PRICE_MYSQL_USER:root}
    password: ${PRICE_MYSQL_PASSWORD:Abc123%}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://127.0.0.1:8761/eureka/}
      preferIpAddress: true

# HTTP Server
server:
  port: 16579  # HTTP (Tomcat) port

swagger:
  controllerPackage: price.controller