spring:
  application:
    name: ts-contacts-service
  datasource:
    url: jdbc:mysql://${CONTACTS_MYSQL_HOST:ts-price-mysql}:${CONTACTS_MYSQL_PORT:3306}/${CONTACTS_MYSQL_DATABASE:ts}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${CONTACTS_MYSQL_USER:root}
    password: ${CONTACTS_MYSQL_PASSWORD:Abc123%}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://127.0.0.1:8761/eureka/}
      preferIpAddress: true

server:
  port: 12347


swagger:
  controllerPackage: contacts.controller