server:
  port: 18885  # HTTP (Tomcat) port

spring:
  application:
    name: ts-cancel-service

swagger:
  controllerPackage: cancel.controller

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://127.0.0.1:8761/eureka/}
      preferIpAddress: true
