server:
  port: 18898

spring:
  application:
    name: ts-seat-service


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://127.0.0.1:8761/eureka/}
      preferIpAddress: true


swagger:
  controllerPackage: seat.controller
