server:
  port: 15680

spring:
  application:
    name: ts-basic-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://127.0.0.1:8761/eureka/}
      preferIpAddress: true


swagger:
  controllerPackage: fdse.microservice.controller