# HTTP Server
server:
  port: 12346  # HTTP (Tomcat) port

spring:
  application:
    name: ts-travel-service
  datasource:
    url: jdbc:mysql://${TRAVEL_MYSQL_HOST:ts-travel-mysql}:${TRAVEL_MYSQL_PORT:3306}/${TRAVEL_MYSQL_DATABASE:ts}?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${TRAVEL_MYSQL_USER:root}
    password: ${TRAVEL_MYSQL_PASSWORD:Abc123%}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

swagger:
  controllerPackage: travel.controller

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:ts-discovery-service:8761}/eureka/

train-service:
  url: http://${TRAIN_SERVICE_HOST:ts-train-service}:${TRAIN_SERVICE_PORT:14567}

order-service:
  url: http://${ORDER_SERVICE_HOST:ts-order-service}:${ORDER_SERVICE_PORT:12031}

route-service:
  url: http://${ROUTE_SERVICE_HOST:ts-route-service}:${ROUTE_SERVICE_PORT:11178}

basic-service:
  url: http://${BASIC_SERVICE_HOST:ts-basic-service}:${BASIC_SERVICE_PORT:15680}

seat-service:
  url: http://${SEAT_SERVICE_HOST:ts-seat-service}:${SEAT_SERVICE_PORT:18898}