# HTTP Server
server:
  port: 14322  # HTTP (Tomcat) port

spring:
  application:
    name: ts-travel-plan-service


swagger:
  controllerPackage: travelplan.controller

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://127.0.0.1:8761/eureka/}
      preferIpAddress: true