server:
  port: 16112

spring:
  application:
    name: ts-admin-order-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://127.0.0.1:8761/eureka/}
      preferIpAddress: true

swagger:
  controllerPackage: adminorder.controller


